AWSTemplateFormatVersion: 2010-09-09
Parameters:
  CfnUrl:
    Description: The key for the SSM parameter containing the full url with
      of the S3 bucket with all of the CloudFormation templates and supporting
      scripts and other components.
    Type: AWS::SSM::Parameter::Value<String>
    Default: /Bootstrap/CloudFormation/S3/Bucket/Url

  AppStreamStackName:
    Description: The name of the AppStream stack.
    Type: String
    Default: Default
    MinLength: 1
    MaxLength: 32
    AllowedPattern: '[a-zA-Z0-9]+'
    ConstraintDescription: Must be between 1 and 32 alphanumeric characters.

  FleetInstanceType:
    Description: The instance type to use when launching both fleet and image 
      builder instances
    Type: String
    Default: stream.standard.medium
    AllowedValues:
      - stream.standard.medium
      - stream.standard.large
      - stream.compute.large
      - stream.compute.xlarge
      - stream.compute.2xlarge
      - stream.compute.4xlarge
      - stream.compute.8xlarge
      - stream.memory.large
      - stream.memory.xlarge
      - stream.memory.2xlarge
      - stream.memory.4xlarge
      - stream.memory.8xlarge
      - stream.memory.z1d.large
      - stream.memory.z1d.xlarge
      - stream.memory.z1d.2xlarge
      - stream.memory.z1d.3xlarge
      - stream.memory.z1d.6xlarge
      - stream.memory.z1d.12xlarge
      - stream.graphics-design.large
      - stream.graphics-design.xlarge
      - stream.graphics-design.2xlarge
      - stream.graphics-design.4xlarge
      - stream.graphics-desktop.2xlarge
      - stream.graphics-pro.4xlarge
      - stream.graphics-pro.8xlarge
      - stream.graphics-pro.16xlarge

  DesiredFleetInstances:
    Description: The Desired Compute Capacity for the Fleet
    Type: Number
    Default: 2

  FleetTypeSetting:
    Description: Whether the AppStream fleet will be always-on or on-demand
    Type: String
    Default: ON_DEMAND
    AllowedValues:
      - ON_DEMAND
      - ALWAYS_ON

  SessionRedirectURL:
    Description: The URL that users are redirected to after their streaming 
      session ends
    Type: String
    Default: http://www.amazon.com

  FleetImageName:
    Description: The name of the AppStream 2.0 image to be used for the fleet.
      i.e GraphicsImage.
    Type: String
    Default: BasicImage

Resources:
  AppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - ${CfnUrl}${Arg1}
        - Arg1: templates/appstream/stack.yaml
      Parameters:
        AppStreamStackName: !Ref AppStreamStackName
        SessionRedirectURL: !Ref SessionRedirectURL
        SamlProviderArn: !Sub '/AppStream/${AppStreamStackName}/IAM/SamlProvider/Arn'

  AppFleet:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - ${CfnUrl}${Arg1}
        - Arg1: templates/appstream/fleet.yaml
      Parameters:
        AppStreamStackName: !Ref AppStreamStackName
        FleetImageName: !Ref FleetImageName
        FleetInstanceType: !Ref FleetInstanceType
        DesiredFleetInstances: !Ref DesiredFleetInstances
        FleetTypeSetting: !Ref FleetTypeSetting
    DependsOn:
      - AppStack
