AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template is intended to be installed into an existing VPC with two 
  public subnets and an Active Directory domain. It will create an auto-scaling 
  group of RD Gateway instances in the public VPC subnets. **WARNING** This 
  template creates Amazon EC2 Windows instance and related resources. You will 
  be billed for the AWS resources used if you create a stack from this 
  template. QS(0006)
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - CfnUrl
      - Label:
          default: Network Configuration
        Parameters:
          - RDGWCIDR
      - Label:
          default: Amazon EC2 Configuration
        Parameters:
          - KeyPairName
          - RDGWInstanceType
          - LatestAmiId
      - Label:
          default: Microsoft Remote Desktop Gateway Configuration
        Parameters:
          - NumberOfRDGWHosts
    ParameterLabels:
      CfnUrl:
        default: CloudFormation S3 Url
      KeyPairName:
        default: Key Pair Name
      LatestAmiId:
        default: SSM Parameter to Grab Latest AMI ID
      NumberOfRDGWHosts:
        default: Number of RDGW Hosts
      RDGWInstanceType:
        default: Remote Desktop Gateway Instance Type
      RDGWCIDR:
        default: Allowed Remote Desktop Gateway External Access CIDR
Parameters:
  CfnUrl:
    Description: The key for the SSM parameter containing the full url with
      of the S3 bucket with all of the CloudFormation templates and supporting
      scripts and other components.
    Type: AWS::SSM::Parameter::Value<String>
    Default: /Bootstrap/CloudFormation/S3/Bucket/Url
  KeyPairName:
    Description: Public/private key pairs allow you to securely connect to 
      your instance after it launches
    Type: AWS::EC2::KeyPair::KeyName
  LatestAmiId:
    Type: String
    Default:
      /aws/service/ami-windows-latest/Windows_Server-2016-English-Full-Base
  NumberOfRDGWHosts:
    AllowedValues:
      - '1'
      - '2'
      - '3'
      - '4'
    Default: '1'
    Description: Enter the number of Remote Desktop Gateway hosts to create
    Type: String
  RDGWInstanceType:
    Description: Amazon EC2 instance type for the Remote Desktop 
      Gateway instances
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.small
      - t2.medium
      - t2.large
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
  RDGWCIDR:
    Description: Allowed CIDR Block for external access to the Remote Desktop 
      Gateways (the more restrictive, the better - NOT 0.0.0.0/0)
    AllowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
    Type: String
Resources:
  # Call the RDP template, passing along the variables populated by request
  # and constructing the SSM parameter keys as required.
  RdpServer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub ${CfnUrl}templates/active-directory/rdp.yaml
      Parameters:
        CfnUrl: !Ref CfnUrl
        KeyPairName: !Ref KeyPairName
        LatestAmiId: !Ref LatestAmiId
        RDGWCIDR: !Ref RDGWCIDR
        NumberOfRDGWHosts: !Ref NumberOfRDGWHosts
        RDGWInstanceType: !Ref RDGWInstanceType
        AdminSecret: /ActiveDirectory/DomainAdmin/SecretsManager/Secret/Id
        DomainDNSName: /ActiveDirectory/Domain/DNS/Name
        DomainNetBIOSName: /ActiveDirectory/Domain/NetBIOS/Name
        DomainMemberSGID: /ActiveDirectory/DomainMember/EC2/SecurityGroup/Id
        PublicSubnet1ID: /Foundation/Public/1/EC2/Subnet/Id
        PublicSubnet2ID: /Foundation/Public/2/EC2/Subnet/Id
        BucketName: /Bootstrap/CloudFormation/S3/Bucket/Name
        BucketKeyPrefix: /Bootstrap/CloudFormation/S3/Bucket/KeyPrefix
        BucketRegion: /Bootstrap/CloudFormation/S3/Bucket/Region
        Vpc: /Foundation/EC2/VPC/Id
