AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DirectoryId:
    Description: The SSM parameter containing the directory identifier
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ActiveDirectory/Domain/DirectoryService/Connector/Id
Resources:
  DomainAdmin:
    Type: AWS::WorkSpaces::Workspace
    Properties:
      UserName: DomainAdmin
      BundleId: wsb-ddkxkghsv
      DirectoryId: !Ref DirectoryId
