AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Env:
    Description: The environment associated with this network (i.e. DEV, PRD).
    Default: ENV
    Type: String
  CidrPrefix:
    Description: The SSM parameter containing the id for the AWS VPC
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ENV/Foundation/EC2/VPC/CidrBlockPrefix
  CidrSuffix1:
    Description: The CIDR block for subnet 1.
    Type: String
  CidrSuffix2:
    Description: The CIDR block for subnet 2.
    Type: String
  MapPublicIpOnLaunch:
    Description: Assign public IP addresses on launch for new instances i
      in the subnet.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  Vpc:
    Description: The SSM parameter containing the id for the AWS VPC
    Type: AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>
    Default: /ENV/Foundation/EC2/VPC/Id
  AvailabilityZone1:
    Description: The SSM parameter containing the first availability zone.
    Type: AWS::SSM::Parameter::Value<AWS::EC2::AvailabilityZone::Name>
    Default: /ENV/Foundation/1/EC2/AvailabilityZone/Name
  AvailabilityZone2:
    Description: The SSM parameter containing the second availability zone.
    Type: AWS::SSM::Parameter::Value<AWS::EC2::AvailabilityZone::Name>
    Default: /ENV/Foundation/2/EC2/AvailabilityZone/Name
  RouteTable1:
    Description: The SSM parameter containing the route table for subnet 1.
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ENV/Foundation/Private/EC2/RouteTable/Id
  RouteTable2:
    Description: The SSM parameter containing the route table for subnet 2.
    Type: AWS::SSM::Parameter::Value<String>
    Default: /ENV/Foundation/Private/EC2/RouteTable/Id
  xCidr1:
    Description: The SSM parameter reference for the first subnet cidr block
    Default: /WORKLOAD/Private/1/EC2/Subnet/CidrBlock
    Type: String
  xCidr2:
    Description: The SSM parameter reference for the second subnet cidr block
    Default: /WORKLOAD/Private/2/EC2/Subnet/CidrBlock
    Type: String
  xSubnet1:
    Description: The SSM parameter reference for the first subnet
    Default: /WORKLOAD/Private/1/EC2/Subnet/Id
    Type: String
  xSubnet2:
    Description: The SSM parameter reference for the second subnet
    Default: /WORKLOAD/Private/2/EC2/Subnet/Id
    Type: String
Resources:
  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Sub ${CidrPrefix}.${CidrSuffix1}
      MapPublicIpOnLaunch: !Ref MapPublicIpOnLaunch
      VpcId: !Ref Vpc
      AvailabilityZone: !Ref AvailabilityZone1
  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Sub ${CidrPrefix}.${CidrSuffix2}
      MapPublicIpOnLaunch: !Ref MapPublicIpOnLaunch
      VpcId: !Ref Vpc
      AvailabilityZone: !Ref AvailabilityZone2
  SubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable1
      SubnetId: !Ref Subnet1
  SubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable2
      SubnetId: !Ref Subnet2
  ParamCidr1:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The cidr block for the first subnet
      Name: !Sub /${Env}${xCidr1}
      Value: !Sub ${CidrPrefix}.${CidrSuffix1}
      Type: String
      Tags:
        Environment: !Ref Env
  ParamCidr2:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The cidr block for the second subnet
      Name: !Sub /${Env}${xCidr2}
      Value: !Sub ${CidrPrefix}.${CidrSuffix2}
      Type: String
      Tags:
        Environment: !Ref Env
  ParamSubnet1:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The id of the first subnet
      Name: !Sub /${Env}${xSubnet1}
      Value: !Ref Subnet1
      Type: String
      Tags:
        Environment: !Ref Env
  ParamSubnet2:
    Type: AWS::SSM::Parameter
    Properties:
      Description: The id of the second subnet
      Name: !Sub /${Env}${xSubnet2}
      Value: !Ref Subnet2
      Type: String
      Tags:
        Environment: !Ref Env
