AWSTemplateFormatVersion: 2010-09-09

Parameters:
  StaticRouteCidr:
    Description: The CIDR range to be routed through the transit gateway
    Type: String
  TransitGateway:
    Description: The SSM parameter reference for the transit gateway id
    Type: AWS::SSM::Parameter::Value<String>
    Default: /Foundation/EC2/TransitGateway/Id
  RouteTable1:
    Description: The cross stack reference for the route table id
    Default: /Foundation/NAT/1/EC2/RouteTable/Id
    Type: AWS::SSM::Parameter::Value<String>
  RouteTable2:
    Description: The cross stack reference for the route table id
    Default: /Foundation/NAT/2/EC2/RouteTable/Id
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  TransitGatewayRoute1:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: !Ref StaticRouteCidr
      RouteTableId: !Ref RouteTable1
      TransitGatewayId: !Ref TransitGateway
  TransitGatewayRoute2:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: !Ref StaticRouteCidr
      RouteTableId: !Ref RouteTable2
      TransitGatewayId: !Ref TransitGateway
